=== jedi-academy/example-xsl/coffee/production.xsd
<?xml version="1.0"?>
<!--
    Schema to constrain the coffee produciton trends
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- 
    ******************************************
    Let's define our types
    ****************************************** 
    -->

    <!-- Lookup code.
    Market and bean codes are defined in the original XML.
    Each of these is a collection of code/name combinations.
    Code uniqueness is specified as part of the collection
    definition, later.
    Each code consists of one or two upper case letters.
    -->
    <xs:simpleType name="Tcode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Z]?"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- A year is a 4-digit integer, except ours have to be >= 2007. -->
    <xs:simpleType name="Tyear">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\d{4}"/>
            <xs:minInclusive value="2007"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- A definition associates a code with a value.  -->
    <xs:complexType name="Tdefinition">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="code" type="Tcode"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- A yes/no restriction.  -->
    <xs:simpleType name="Tyesno">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Y"/>
            <xs:enumeration value="N"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- 
    ******************************************
    Let's define our structure
    ****************************************** 
    -->

    <!-- production
    The root element is *production*.
    It defines region codes, then contains
    data for each region.
    -->
    <xs:element name="production">        
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="codes"/>        
                <xs:element ref="region" maxOccurs="unbounded"/>        
            </xs:sequence>
            <xs:attribute name="source" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Region codes.
    The *regions* element contains entries for each region coffee is grown in.
    -->
    <xs:element name="codes">        
        <xs:complexType>
            <xs:sequence>
                <xs:element name="area" type="Tdefinition" maxOccurs="unbounded"/>        
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="regioncodes">
            <xs:selector xpath="area"/>
            <xs:field xpath="@code"/>
        </xs:unique>
    </xs:element>

    <!-- A *region* element contains the countries in that region -->
    <xs:element name="region">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="country" maxOccurs="unbounded"/>        
            </xs:sequence>
            <xs:attribute name="code" type="Tcode" use="optional"/>
        </xs:complexType>
        <!-- we can't bind the code to the definitions, but we can insist 
        they be unique, i.e. only region element per area. -->
        <xs:unique name="regioncodesused">
            <xs:selector xpath="."/>
            <xs:field xpath="@code"/>
        </xs:unique>
    </xs:element>

    <!-- Each *country* element provides the country name, and then annual production values. -->
    <xs:element name="country">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />        
                <xs:element ref="value" maxOccurs="unbounded" />        
            </xs:sequence>
             <xs:attribute name="member" type="Tyesno" default="Y"/>
       </xs:complexType>
    </xs:element>

    <!-- Each *value* element provides the annual production for a country.  -->
    <xs:element name="value">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="year" type="Tyear"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>


    
</xs:schema>

=== jedi-academy/example-xsl/coffee/production.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='production.xsl'?>
<!--
production.xml

This XML document is a record of historical coffee bean production, in 000s of 60kg bags.
Original data came from the International Coffee Organization
HREF: www.ico.org/prices/p2.htm
-->

<production source="www.ico.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="production.xsd">
    
    <codes>
        <area code="SA">South America</area>
        <area code="CA">Central America</area>
        <area code="A">Africa</area>
        <area code="P">Pacific</area>
    </codes>
    
    <region code="A">
        <country>
            <name>Angola</name>
            <value year="2007">36</value>
            <value year="2008">38</value>
            <value year="2009">13</value>
            <value year="2010">35</value>
            <value year="2011">29</value>
            <value year="2012">33</value>
        </country>
        <country>
            <name>Burundi</name>
            <value year="2007">133</value>
            <value year="2008">412</value>
            <value year="2009">112</value>
            <value year="2010">353</value>
            <value year="2011">204</value>
            <value year="2012">406</value>
        </country>
        <country>
            <name>Cameroon</name>
            <value year="2007">795</value>
            <value year="2008">725</value>
            <value year="2009">902</value>
            <value year="2010">503</value>
            <value year="2011">574</value>
            <value year="2012">635</value>
        </country>
        <country>
            <name>Central African Republic</name>
            <value year="2007">43</value>
            <value year="2008">60</value>
            <value year="2009">93</value>
            <value year="2010">95</value>
            <value year="2011">86</value>
            <value year="2012">100</value>
        </country>
        <country member="N">
            <name>Congo, Demo Rep of</name>
            <value year="2007">416</value>
            <value year="2008">422</value>
            <value year="2009">346</value>
            <value year="2010">305</value>
            <value year="2011">357</value>
            <value year="2012">450</value>
        </country>
        <country>
            <name>Cote d'Ivoire</name>
            <value year="2007">2317</value>
            <value year="2008">2397</value>
            <value year="2009">1795</value>
            <value year="2010">982</value>
            <value year="2011">1886</value>
            <value year="2012">2000</value>
        </country>
        <country>
            <name>Ethiopia</name>
            <value year="2007">5967</value>
            <value year="2008">4949</value>
            <value year="2009">6931</value>
            <value year="2010">7500</value>
            <value year="2011">6798</value>
            <value year="2012">8100</value>
        </country>
        <country>
            <name>Gabon</name>
            <value year="2007">0</value>
            <value year="2008">1</value>
            <value year="2009">1</value>
            <value year="2010">1</value>
            <value year="2011">0</value>
            <value year="2012">1</value>
        </country>
        <country>
            <name>Ghana</name>
            <value year="2007">31</value>
            <value year="2008">27</value>
            <value year="2009">33</value>
            <value year="2010">112</value>
            <value year="2011">146</value>
            <value year="2012">85</value>
        </country>
        <country member="N">
            <name>Guinea</name>
            <value year="2007">323</value>
            <value year="2008">505</value>
            <value year="2009">499</value>
            <value year="2010">386</value>
            <value year="2011">351</value>
            <value year="2012">415</value>
        </country>
        <country>
            <name>Kenya</name>
            <value year="2007">652</value>
            <value year="2008">541</value>
            <value year="2009">630</value>
            <value year="2010">658</value>
            <value year="2011">680</value>
            <value year="2012">767</value>
        </country>
        <country>
            <name>Liberia</name>
            <value year="2007">7</value>
            <value year="2008">12</value>
            <value year="2009">13</value>
            <value year="2010">10</value>
            <value year="2011">11</value>
            <value year="2012">10</value>
        </country>
        <country member="N">
            <name>Madagascar</name>
            <value year="2007">614</value>
            <value year="2008">728</value>
            <value year="2009">457</value>
            <value year="2010">530</value>
            <value year="2011">604</value>
            <value year="2012">530</value>
        </country>
        <country>
            <name>Malawi</name>
            <value year="2007">19</value>
            <value year="2008">21</value>
            <value year="2009">17</value>
            <value year="2010">17</value>
            <value year="2011">27</value>
            <value year="2012">20</value>
        </country>
        <country>
            <name>Rwanda</name>
            <value year="2007">224</value>
            <value year="2008">369</value>
            <value year="2009">259</value>
            <value year="2010">323</value>
            <value year="2011">247</value>
            <value year="2012">209</value>
        </country>
        <country>
            <name>Sierra Leone</name>
            <value year="2007">40</value>
            <value year="2008">86</value>
            <value year="2009">91</value>
            <value year="2010">33</value>
            <value year="2011">76</value>
            <value year="2012">50</value>
        </country>
        <country>
            <name>Tanzania</name>
            <value year="2007">810</value>
            <value year="2008">1186</value>
            <value year="2009">675</value>
            <value year="2010">846</value>
            <value year="2011">534</value>
            <value year="2012">1017</value>
        </country>
        <country>
            <name>Togo</name>
            <value year="2007">125</value>
            <value year="2008">138</value>
            <value year="2009">202</value>
            <value year="2010">160</value>
            <value year="2011">162</value>
            <value year="2012">150</value>
        </country>
        <country>
            <name>Uganda</name>
            <value year="2007">3449</value>
            <value year="2008">3290</value>
            <value year="2009">2845</value>
            <value year="2010">3203</value>
            <value year="2011">2817</value>
            <value year="2012">3200</value>
        </country>
        <country>
            <name>Yemen</name>
            <value year="2007">198</value>
            <value year="2008">220</value>
            <value year="2009">135</value>
            <value year="2010">161</value>
            <value year="2011">166</value>
            <value year="2012">200</value>
        </country>
        <country>
            <name>Zambia</name>
            <value year="2007">61</value>
            <value year="2008">35</value>
            <value year="2009">28</value>
            <value year="2010">13</value>
            <value year="2011">10</value>
            <value year="2012">10</value>
        </country>
        <country>
            <name>Zimbabwe</name>
            <value year="2007">31</value>
            <value year="2008">24</value>
            <value year="2009">21</value>
            <value year="2010">10</value>
            <value year="2011">9</value>
            <value year="2012">9</value>
        </country>
    </region>


    <region code="CA">
        <country>
            <name>Costa Rica</name>
            <value year="2007">1771</value>
            <value year="2008">1287</value>
            <value year="2009">1304</value>
            <value year="2010">1392</value>
            <value year="2011">1462</value>
            <value year="2012">1671</value>
        </country>
        <country>
            <name>Cuba</name>
            <value year="2007">7</value>
            <value year="2008">12</value>
            <value year="2009">22</value>
            <value year="2010">26</value>
            <value year="2011">38</value>
            <value year="2012">100</value>
        </country>
        <country member="N">
            <name>Dominican Republic</name>
            <value year="2007">465</value>
            <value year="2008">645</value>
            <value year="2009">352</value>
            <value year="2010">378</value>
            <value year="2011">682</value>
            <value year="2012">550</value>
        </country>
        <country>
            <name>El Salvador</name>
            <value year="2007">1505</value>
            <value year="2008">1410</value>
            <value year="2009">1065</value>
            <value year="2010">1814</value>
            <value year="2011">1152</value>
            <value year="2012">1242</value>
        </country>
        <country>
            <name>Guatemala</name>
            <value year="2007">4100</value>
            <value year="2008">3785</value>
            <value year="2009">3835</value>
            <value year="2010">3950</value>
            <value year="2011">3840</value>
            <value year="2012">3143</value>
        </country>
        <country member="N">
            <name>Haiti</name>
            <value year="2007">359</value>
            <value year="2008">359</value>
            <value year="2009">351</value>
            <value year="2010">350</value>
            <value year="2011">349</value>
            <value year="2012">325</value>
        </country>
        <country>
